configuration :
  - name : alice
    ip   : localhost
    port : 12344 # This is the incoming port on which MP will listen
               # May be changed for further communication as usual
  - name : bob
    ip   : localhost
    port : 14255
  - name : charlie
    ip   : 128.237.219.93
    port : 12998
  - name : daphnie
    ip   : 128.237.217.222
    port : 1987 

sendRules :
  - action : drop # Ack message number 4 from bob to alice will not be sent
    src    : bob
    dest   : alice
    kind   : Ack
    seqNum : 4
    duplicate : true
  - action : delay # Every Lookup message in the system will be delayed
    kind   : Lookup 

receiveRules :
  - action : duplicate # 3rd message from Charlie that anyone
    src    : charlie # receives will be duplicated
    seqNum : 3
  - action : drop
    duplicate : true