groups : # A single, top-level section in the YAML file
  - name : Group1 # Group names must be unique
    members : # Any number of members in the group
      - alice 
      - bob
      - charlie
  - name : Group2 
    members :    
      - daphnie
      - bob
      - charlie
      
configuration :
  - name : alice
    ip   : localhost
    port : 12344 # This is the incoming port on which MP will listen
               # May be changed for further communication as usual
  - name : bob
    ip   : localhost
    port : 14255
  - name : charlie
    ip   : 128.237.219.93
    port : 12998
  - name : daphnie
    ip   : 128.237.217.222
    port : 1987 
  - name : logger
    ip   : localhost
    port : 54637  

sendRules :
  - action : drop # Ack message number 4 from bob to alice will not be sent
    src    : bob
    dest   : bob
    kind   : Ack
    seqNum : 1
  - action : delay # Every Lookup message in the system will be delayed
    kind   : Lookup 

receiveRules :
  - action : duplicate # 3rd message from Charlie that anyone
    src    : charlie # receives will be duplicated
    seqNum : 3
  - action : drop
    duplicate : true